---
- name: playbook to install mariadb-server
  hosts: dbservers
  vars:
    config_file_url: https://drive.google.com/uc?export=download&id=1QIeumZzk1_PL6pVf699ff8iurEnuwk7y
    config_file_dst: /etc/mysql/my.cnf
  tasks:
    - name: install mariadb
      ansible.builtin.yum:
        name:
          - mariadb-server
          - python3-PyMySQL
        state: present
      notify:
        - set db password

    - name: start mariadb
      ansible.builtin.service:
        name: mariadb
        enabled: true
        state: started

    - name: install "{{config_file_dst}}" file
      ansible.builtin.get_url:
        url: "{{config_file_url}}"
        dest: "{{config_file_dst}}"
        owner: root
        group: root
      notify:
        - restart db service

  handlers:
    - name: restart db service
      ansible.builtin.service:
        name: mariadb
        state: restarted

    - name: set db password
      ansible.builtin.mysql_user:
        name: "{{username}}"
        password: "{{password}}"
